name: 清理Actions运行记录
on:
  workflow_dispatch:
    inputs:
      clean_type:
        description: '0=全部 1=失败 2=取消 3=失败+取消'
        required: true
        default: '1'
        type: choice
        options:
          - '0'
          - '1'
          - '2'
          - '3'
      runner_filter:
        description: 'Repo=只删Repo 其他=删非Repo'
        required: true
        type: choice
        options:
          - 'Repo'
          - '其他所有'

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 清理记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          retain_days: 0
          keep_minimum_runs: 0
          dry_run: false
